param(
  [string]$Repo = (Split-Path -Parent $PSScriptRoot),
  [string]$OutDir = $null
)
$ErrorActionPreference = 'Stop'
if (-not $OutDir) { $OutDir = Join-Path $Repo 'single\meArm' }
New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
$outFile = Join-Path $OutDir 'meArm.ino'

# Keep dependency order explicit: declarations first, then implementations, sketch entry last.
$headers = @(
  'weArm_config.h', 'constant_and_positions.h', 'protocol_constants.h',
  'servo_drive.h', 'move.h', 'serial_protocol.h', 'pick_place.h',
  'button_control.h', 'draw_control.h', 'joystick_control.h', 'path_core.h'
)
$sources = @(
  'servo_drive.cpp', 'constant_and_positions.cpp', 'protocol_constants.cpp',
  'move.cpp', 'joystick_control.cpp', 'pick_place.cpp',
  'draw_control.cpp', 'button_control.cpp', 'serial_protocol.cpp'
)
$sketch = 'meArm.ino'
$seenSystem = @{}
$chunks = New-Object System.Collections.Generic.List[string]
$chunks.Add('// Generated by .selfcheck/make_single.ps1. Do not edit this file directly.')
$chunks.Add('#include <Arduino.h>')

function Add-Source([string]$name) {
  $path = Join-Path $Repo $name
  if (-not (Test-Path -LiteralPath $path)) { throw "missing source: $path" }
  $lines = [System.IO.File]::ReadAllLines($path, [System.Text.UTF8Encoding]::new($false))
  $kept = New-Object System.Collections.Generic.List[string]
  foreach ($line in $lines) {
    if ($name -eq 'draw_control.cpp' -and $line -match '\bclampDouble\b') {
      $line = $line -replace '\bclampDouble\b', 'drawClampDouble'
    }
    if ($line -match '^\s*#\s*include\s+"[^"]+"') { continue }
    if ($line -match '^\s*#\s*include\s+<Arduino\.h>') { continue }
    if ($line -match '^\s*#\s*include\s+<([^>]+)>') {
      $inc = $matches[1]
      if ($seenSystem.ContainsKey($inc)) { continue }
      $seenSystem[$inc] = $true
    }
    $kept.Add($line)
  }
  $chunks.Add("`n// ===== $name =====")
  foreach ($line in $kept) { $chunks.Add($line) }
}
foreach ($name in $headers) { Add-Source $name }
foreach ($name in $sources) { Add-Source $name }
Add-Source $sketch
# Write LF-only on purpose: .gitattributes declares "* text=auto eol=lf", so LF is what a
# checkout produces. Matching it keeps the on-disk artifact byte-identical to the committed
# blob (WriteAllLines would have emitted CRLF on Windows and forced git to normalise).
$text = [string]::Join("`n", $chunks) + "`n"
[System.IO.File]::WriteAllText($outFile, $text, [System.Text.UTF8Encoding]::new($false))
# NOTE: $chunks.Count is NOT the line count: every banner chunk is "\n// ===== name =====" and
# therefore expands to two lines (a blank line plus the banner). Count the written text instead,
# otherwise this message drifts from the real file (and docs quote the line count in 表 1).
$lineCount = $text.Split("`n").Length - 1
Write-Host ("generated {0} ({1} bytes, {2} lines)" -f $outFile, (Get-Item -LiteralPath $outFile).Length, $lineCount)
